version: "3.8"
services:
  streamlit:
    image: rylorin/streamlit-docker:latest
    ports:
    - 8501:8501/tcp
    environment:
      GIT_URL: ${GIT_URL:-https://github.com/streamlit/streamlit-example.git}
    networks:
      - default
      - system_dmz_network

networks:
  default:
  system_dmz_network:
    external: true
