name: Deploy to docker hub

on:
  push:
    branches:
      - '*' 
      - '!feature/**' 
      - '!hotfix/**'
      - '!bugfix/**'
      - '!dev'
    tags:
      - 'v*'
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "docker-stack.yml"
      - ".github/workflows/build-test.yml"
      - "test/**"
  schedule:
    - cron: "0 3 * * 0" # Runs at 03:00 AM (UTC) every Sunday

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        IBG_VERSION: [stable, latest]
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ github.repository }}:${{ matrix.IBG_VERSION }}
          context: .
          build-args: IBG_VERSION=${{ matrix.IBG_VERSION }}
#          platforms: linux/amd64,linux/arm64v8
